version: "3.9"

services:
  video2carla:
    build:
      args:
        PLATFORM: ${PLATFORM:-cpu}
    image: wielgoszinfo/pedestrians-video-2-carla:${PLATFORM:-cpu}-latest
    environment:
      COMMIT: ${COMMIT}
    deploy: null
    depends_on: []
