common_params:
  mode: train
  flow: autoencoder
  data_module_name: CarlaRecorded
  trajectory_model_name: ZeroTrajectory
  logs_dir: /runs/carla-recorded_autoencoder_tests
  seed: 22742
  log_every_n_steps: 10
  batch_size: 2048
  renderers: none
  skip_metadata: null
  num_sanity_val_steps: 1
  clip_offset: 15
  clip_length: 15
  gpus: 1
  auto_select_gpus: True
  max_epochs: 5000
  transform: bbox
  noise_param: 1.0
  enable_progress_bar: True
compare_params:
  movements_model_name:
    - LinearAE2D
    - LSTM
    - Seq2Seq
    - Seq2SeqEmbeddings
  noise:
    - zero
    - gaussian
  missing_point_probability:
    - 0.0
    - 0.1
common_model:
  Seq2Seq:
    teacher_mode: frames_force
    teacher_force_ratio: 0.5
    teacher_force_drop: 0.002
    hidden_size: 128
    movements_output_type: pose_2d
  Seq2SeqEmbeddings:
    teacher_mode: frames_force
    teacher_force_ratio: 0.5
    teacher_force_drop: 0.002
    single_joint_embeddings_size: 16
    hidden_size: 128
    movements_output_type: pose_2d
  LSTM:
    hidden_size: 128
    movements_output_type: pose_2d
compare_model:
  Seq2Seq:
    num_layers:
      - 2
      - 3
  Seq2SeqEmbeddings:
    num_layers:
      - 2
      - 3
  LSTM:
    num_layers:
      - 2
      - 3
  LinearAE2D:
    model_scaling_factor:
      - 8
      - 4