program: src/pedestrians_video_2_carla/modeling.py
project: autoencoder
entity: carla-pedestrians
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --skip_metadata
  - --disable_lr_scheduler
  - --strong_points
method: bayes
metric:
  goal: maximize
  name: hp/PCKhn@01
parameters:
  mode:
    value: train
  flow:
    value: autoencoder
  data_module_name:
    value: JAADOpenPose
  log_every_n_steps:
    value: 10
  num_sanity_val_steps:
    value: 1
  max_epochs:
    value: 1500
  enable_progress_bar:
    value: False
  lr:
    max: 0.01
    min: 0.001
    distribution: uniform
  movements_model_name:
    value: LSTM
  renderers:
    value: none
  movements_output_type:
    value: pose_2d
  clip_offset:
    value: 4
  clip_length:
    value: 4
  batch_size:
    value: 256
  hidden_size:
    max: 512
    min: 64
    distribution: int_uniform
  num_layers:
    max: 4
    min: 1
    distribution: int_uniform
  transform:
    value: hips_neck_bbox
  missing_point_probability:
    value: 0.1
  noise_param:
    value: 1.0
  noise:
    value: gaussian
  input_nodes:
    value: BODY_25_SKELETON
  output_nodes:
    value: BODY_25_SKELETON